-- 공휴일 테이블 생성
CREATE SEQUENCE HOLIDAY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE HOLIDAY (
  HOLIDAY_ID   NUMBER        PRIMARY KEY,
  HOLIDAY_DATE DATE          NOT NULL,
  HOLIDAY_NAME VARCHAR2(100) NOT NULL,
  CREATED_BY   VARCHAR2(50),
  CONSTRAINT UQ_HOLIDAY UNIQUE (HOLIDAY_DATE)
);

COMMIT;
